
Fine-tuning gpt2...
Traceback (most recent call last):
  File "/users5/znchen/distil/ft_frame.py", line 283, in <module>
    main()
  File "/users5/znchen/distil/ft_frame.py", line 268, in main
    finetune_frame(args.dataset_class,args.train_data, args.dev_data, model_name=args.model_name, batch_size=batch_size, num_epochs=args.epochs, learning_rate=args.learning_rate)
NameError: name 'batch_size' is not defined